version: '3'
services:
  test:
    image: tedris/about-me-build:latest
    container_name: test
    entrypoint:
      - go
      - test
      - -p
      - '1'
      - -v
      - -tags=unit
      - ./...